### PR TITLE
Dev/version1

### PR DESCRIPTION
**Pull request by abolfazl8131**
I tried to automate the vagrant and virtual box installation by adding a simple script in the scripts folder and triggering it at the start.sh

### CODE REVIEW

**Comment by Shayan-Ghani** [comment]
plz provide a description for your pr following semantic versioning, 
link the issue you're trying to solve

**Comment by abolfazl8131** [comment]
Certainly, there is no issue i tried to solve. I've just added a simple
script for some automation as I added in the description

**Comment by Shayan-Ghani** [comment]
Alright, LGTM but next time start your pr description in the following way:

fix Vagrant and virtualbox installation

**Review by Shayan-Ghani — APPROVED** [review]
LGTM

**Pull request merged**
